spring:
  datasource:
    url: jdbc:postgresql://localhost:25432/postgres
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update